#!/bin/bash

OLDPATH=$PATH
WORKDIR="$(cd $(dirname $0) && pwd)"
cd "$WORKDIR"

[[ -z "$DEPLOYHOST" ]] && echo "Please set env `DEPLOYHOST`" && exit 1

[[ -n "$@" ]] && PROJECTS="$@" || PROJECTS="utils debug poi game"
for p in $PROJECTS; do
    printf "======== %5s ========\n" $p
    pushd $p
    export PATH="$WORKDIR/$p/node_modules/.bin":$OLDPATH
    babel src -d app
    rsync -avP app index.js package.json package-lock.json $DEPLOYHOST:/app/qqbot/$p/
    popd
done